mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.faken.aiproject.po.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ai_db
  redis:
    database: 0
    url: redis://localhost:6379/0
email:
  host: smtp.qq.com
  password: ecxcdzqqmwslddcj
  username: 3087609114@qq.com
  port: 587