mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.faken.aiproject.po.entity
    configuration:
      map-underscore-to-camel-case: true
server:
    port: 8080
spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/ai_db
    redis:
      host: localhost
      port: 6379
      database: 0
      username: default
      password: 123456
email:
  host: smtp.qq.com
  password: ecxcdzqqmwslddcj
  username: 3087609114@qq.com
  port: 587
huawei-obs:
  ak: F915WYG9INM7JCMKWYA8
  sk: bWMR0xxcVBxOA6URk86efzREAOXLzoZvu6lkU00M
  end-point: https://obs.cn-south-1.myhuaweicloud.com
  bucket-name: qg23onnx